{
	"name": "cd",
	"on": {
		"push": {
			"branches": ["main"]
		}
	},
	"concurrency": {
		"group": "${{ github.ref }}",
		"cancel-in-progress": true
	},
	"permissions": {
		"contents": "read",
		"pages": "write",
		"id-token": "write"
	},
	"jobs": {
		"deploy": {
			"runs-on": "ubuntu-latest",
			"environment": {
				"name": "github-pages",
				"url": "${{ steps.deploy.outputs.page_url }}"
			},
			"steps": [
				{ "uses": "actions/checkout@v4", "with": { "ref": "main" } },
				{ "uses": "actions/setup-node@v4", "with": { "node-version": "lts/*" } },
				{ "uses": "pnpm/action-setup@v4", "with": { "version": "latest", "run_install": false } },
				{
					"uses": "actions/cache@v4",
					"with": {
						"path": "~/.pnpm-store",
						"key": "pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}",
						"restore-keys": "pnpm-store-${{ runner.os }}-"
					}
				},
				{ "run": "pnpm config set --location=project --json allowBuilds \"{ \\\"esbuild\\\": true }\"" },
				{ "run": "pnpm config set --location=project strict-dep-builds false" },
				{ "env": { "PAT": "${{ secrets.PAT }}", "run": "pnpm install" } },
				{ "run": "pnpm run build" },
				{
					"uses": "brianjenkins94/lib/.github/actions/pages-deploy@main",
					"id": "deploy",
					"with": { "path": "docs" }
				}
			],
			"timeout-minutes": 15
		}
	}
}
